### ISSUE TITLE
@amielke.de is no longer valid

### ISSUE THREAD

**Issue by mgorny** [amielke/amielke-overlay#5]
Hello,

It seems that your domain has expired (?). This means that both your homepage is no longer valid, and the contact address is no longer reachable. Worse than that, it seems that you still use @amielke.de e-mail address for bugs.gentoo.org.

Please change the bugs.gentoo.org e-mail address ASAP, and then let me know to what address I should set the contact/owner e-mail for your overlay in repositories.xml, and the new homepage (possibly github).

**Comment by amielke** [comment]
The domain is still correct. I have no content on the page. But all mails come with me.

I hope so ok.

Regards Andreas

PS. www.denic.de  Whois query

**Comment by mgorny** [comment]
Well, this one is invalid:

```
<overlay@amielke.de>: host mail.amielke.de[178.254.4.101] said: 550 unknown
    user (in reply to RCPT TO command)
```

If the Bugzilla address is valid, is it ok to change the overlay contact address to that?

**Comment by amielke** [comment]
Hi, 

I deleted the email address by mistake.

I think now it's true again.

**Comment by mgorny** [comment]
Ok, re-sent the mail. But long story short, it says that you're required to use a Bugzilla-registered address for overlay contact.

**Comment by amielke** [comment]
Hello again,

Can you change the email address to gentoo@amielke.de?

This is my bug account on bugs.gentoo.de

Then it should be perfect.

Thanks Andreas.




My NEW repositories.xml

<repositories encoding="unicode" version="1.0">
  <repo priority="50" quality="experimental" status="unofficial">
    <name>amielke-overlay</name>
    <description>Overlay with focus on VDR and software that is not in Portage</description>
    <homepage>http://amielke.de/</homepage>;
    <owner>
      <email>gentoo@amielke.de</email>
      <name>Andreas Mielke</name>
    </owner>
    <source type="git">git://github.com/amielke/amielke-overlay.git</source>
    <feed>http://github.com/feeds/amielke/commits/amielke-overlay/master</feed>;
  </repo>


My Old repositories.xml

<repositories encoding="unicode" version="1.0">
  <repo priority="50" quality="experimental" status="unofficial">
    <name>amielke-overlay</name>
    <description>Overlay with focus on VDR and software that is not in Portage</description>
    <homepage>http://amielke.de/</homepage>;
    <owner>
      <email>overlay@amielke.de</email>
      <name>Andreas Mielke</name>
    </owner>
    <source type="git">git://github.com/amielke/amielke-overlay.git</source>
    <feed>http://github.com/feeds/amielke/commits/amielke-overlay/master</feed>;
  </repo>

**Comment by mgorny** [comment]
Done, thanks.
